name: Release

on:
  release:
    types: [published]
    
jobs:
  Package:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Authenticate
      shell: pwsh
      env: 
        RELEASE_KEY: ${{ secrets.RELEASE_KEY }}
      run: dotnet nuget add source https://nuget.pkg.github.com/bcolemutech/index.json -n github -u bcolemutech -p "$env:RELEASE_KEY"
    - name: SetTag
      shell: pwsh
      env:
        RELEASE_TAG: ${{github.ref}}
      run: $env:RELEASE_TAG = $env:RELEASE_TAG -replace "/refs/tags/", ""
    - name: Pack
      shell: pwsh
      run: dotnet pack dol-sdk/dol-sdk.csproj -p:PackageVersion=$env:RELEASE_TAG --configuration Release
    - name: Publish
      shell: pwsh
      run: dotnet nuget push "bin/Release/dol-sdk.$env:RELEASE_TAG.nupkg" --source "github"
      